unit TestNumber2StringUnit;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  TestFramework,
  SysUtils,
  Number2StringUnit,
  ConcreteCollectionsUnit;

type
  TestTEnglishNumber2DecimalString = class(TTestCase)
  strict private
    FMatches: TInt64StringPairList;
    FNumber2String: INumber2String;
  strict protected
    property Number2String: INumber2String read FNumber2String;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestNumber2String;
  end;

  TestTDutchNumber2DecimalString = class(TTestCase)
  strict private
    FMatches: TInt64StringPairList;
    FNumber2String: INumber2String;
  strict protected
    procedure AddMatches;
    function CreateNumber2String: INumber2String;
    property Number2String: INumber2String read FNumber2String;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestNumber2String;
  end;

  TestTGermanNumber2DecimalString = class(TTestCase)
  strict private
    FMatches: TInt64StringPairList;
    FNumber2String: INumber2String;
  strict protected
    procedure AddMatches;
    function CreateNumber2String: INumber2String;
    property Number2String: INumber2String read FNumber2String;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestNumber2String;
  end;

implementation

procedure TestTEnglishNumber2DecimalString.SetUp;
begin
  inherited;
  FNumber2String := TEnglishNumber2DecimalString.Create;
  FMatches := TInt64StringPairList.Create();
  FMatches.Add(TInt64StringPair.Create(TAbstractNumber2DecimalString.Zero, 'zero'));
  FMatches.Add(TInt64StringPair.Create(20000000000, 'twenty billions')); // (2 * 10^11)
  // from Roman:
  FMatches.Add(TInt64StringPair.Create(0, 'zero'));
  FMatches.Add(TInt64StringPair.Create(1, 'one'));
  FMatches.Add(TInt64StringPair.Create(2, 'two'));
  FMatches.Add(TInt64StringPair.Create(3, 'three'));
  FMatches.Add(TInt64StringPair.Create(4, 'four'));
  FMatches.Add(TInt64StringPair.Create(5, 'five'));
  FMatches.Add(TInt64StringPair.Create(6, 'six'));
  FMatches.Add(TInt64StringPair.Create(7, 'seven'));
  FMatches.Add(TInt64StringPair.Create(8, 'eight'));
  FMatches.Add(TInt64StringPair.Create(9, 'nine'));
  FMatches.Add(TInt64StringPair.Create(10, 'ten'));
  FMatches.Add(TInt64StringPair.Create(11, 'eleven'));
  FMatches.Add(TInt64StringPair.Create(12, 'twelve'));
  FMatches.Add(TInt64StringPair.Create(13, 'thirteen'));
  FMatches.Add(TInt64StringPair.Create(14, 'fourteen'));
  FMatches.Add(TInt64StringPair.Create(15, 'fifteen'));
  FMatches.Add(TInt64StringPair.Create(16, 'sixteen'));
  FMatches.Add(TInt64StringPair.Create(17, 'seventeen'));
  FMatches.Add(TInt64StringPair.Create(18, 'eighteen'));
  FMatches.Add(TInt64StringPair.Create(19, 'nineteen'));
  FMatches.Add(TInt64StringPair.Create(20, 'twenty'));
  FMatches.Add(TInt64StringPair.Create(21, 'twenty one'));
  FMatches.Add(TInt64StringPair.Create(25, 'twenty five'));
  FMatches.Add(TInt64StringPair.Create(30, 'thirty'));
  FMatches.Add(TInt64StringPair.Create(35, 'thirty five'));
  FMatches.Add(TInt64StringPair.Create(40, 'forty'));
  FMatches.Add(TInt64StringPair.Create(45, 'forty five'));
  FMatches.Add(TInt64StringPair.Create(49, 'forty nine'));
  FMatches.Add(TInt64StringPair.Create(50, 'fifty'));
  FMatches.Add(TInt64StringPair.Create(60, 'sixty'));
  FMatches.Add(TInt64StringPair.Create(69, 'sixty nine'));
  FMatches.Add(TInt64StringPair.Create(70, 'seventy'));
  FMatches.Add(TInt64StringPair.Create(76, 'seventy six'));
  FMatches.Add(TInt64StringPair.Create(80, 'eighty'));
  FMatches.Add(TInt64StringPair.Create(90, 'ninety'));
  FMatches.Add(TInt64StringPair.Create(99, 'ninety nine'));
  FMatches.Add(TInt64StringPair.Create(100, 'one hundred'));
  FMatches.Add(TInt64StringPair.Create(110, 'one hundred ten'));
  FMatches.Add(TInt64StringPair.Create(150, 'one hundred fifty'));
  FMatches.Add(TInt64StringPair.Create(200, 'two hundred'));
  FMatches.Add(TInt64StringPair.Create(300, 'three hundred'));
  FMatches.Add(TInt64StringPair.Create(400, 'four hundred'));
  FMatches.Add(TInt64StringPair.Create(499, 'four hundred ninety nine'));
  FMatches.Add(TInt64StringPair.Create(500, 'five hundred'));
  FMatches.Add(TInt64StringPair.Create(600, 'six hundred'));
  FMatches.Add(TInt64StringPair.Create(666, 'six hundred sixty six'));
  FMatches.Add(TInt64StringPair.Create(700, 'seven hundred'));
  FMatches.Add(TInt64StringPair.Create(800, 'eight hundred'));
  FMatches.Add(TInt64StringPair.Create(900, 'nine hundred'));
  FMatches.Add(TInt64StringPair.Create(999, 'nine hundred ninety nine'));
  FMatches.Add(TInt64StringPair.Create(1000, 'one thousand'));
  FMatches.Add(TInt64StringPair.Create(1444, 'one thousand four hundred forty four'));
  FMatches.Add(TInt64StringPair.Create(1666, 'one thousand six hundred sixty six'));
  FMatches.Add(TInt64StringPair.Create(1990, 'one thousand nine hundred ninety'));
  FMatches.Add(TInt64StringPair.Create(1999, 'one thousand nine hundred ninety nine'));
  FMatches.Add(TInt64StringPair.Create(2000, 'two thousand'));
  FMatches.Add(TInt64StringPair.Create(2001, 'two thousand one'));
  FMatches.Add(TInt64StringPair.Create(2010, 'two thousand ten'));
  FMatches.Add(TInt64StringPair.Create(2012, 'two thousand twelve'));
  FMatches.Add(TInt64StringPair.Create(2500, 'two thousand five hundred'));
  FMatches.Add(TInt64StringPair.Create(3000, 'three thousand'));
  FMatches.Add(TInt64StringPair.Create(3888, 'three thousand eight hundred eighty eight'));
  FMatches.Add(TInt64StringPair.Create(3999, 'three thousand nine hundred ninety nine'));
  FMatches.Add(TInt64StringPair.Create(4000, 'four thousand'));
  FMatches.Add(TInt64StringPair.Create(5000, 'five thousand'));
  FMatches.Add(TInt64StringPair.Create(6666, 'six thousand six hundred sixty six'));
  FMatches.Add(TInt64StringPair.Create(10000, 'ten thousand'));
  FMatches.Add(TInt64StringPair.Create(50000, 'fifty thousand'));
  FMatches.Add(TInt64StringPair.Create(100000, 'one hundred thousand'));
  FMatches.Add(TInt64StringPair.Create(500000, 'five hundred thousand'));
  FMatches.Add(TInt64StringPair.Create(1000000, 'one million'));
  FMatches.Add(TInt64StringPair.Create(1444000, 'one million four hundred forty four thousand'));
  FMatches.Add(TInt64StringPair.Create(1666000, 'one million six hundred sixty six thousand'));
  FMatches.Add(TInt64StringPair.Create(2000000, 'two millions'));
  FMatches.Add(TInt64StringPair.Create(3888000, 'three millions eight hundred eighty eight thousand'));
  FMatches.Add(TInt64StringPair.Create(-3888000, 'minus three millions eight hundred eighty eight thousand'));
  // http://www.rgagnon.com/javadetails/java-0426.html
  FMatches.Add(TInt64StringPair.Create(0, 'zero'));
  FMatches.Add(TInt64StringPair.Create(1, 'one'));
  FMatches.Add(TInt64StringPair.Create(16, 'sixteen'));
  FMatches.Add(TInt64StringPair.Create(100, 'one hundred'));
  FMatches.Add(TInt64StringPair.Create(118, 'one hundred eighteen'));
  FMatches.Add(TInt64StringPair.Create(200, 'two hundred'));
  FMatches.Add(TInt64StringPair.Create(219, 'two hundred nineteen'));
  FMatches.Add(TInt64StringPair.Create(800, 'eight hundred'));
  FMatches.Add(TInt64StringPair.Create(801, 'eight hundred one'));
  FMatches.Add(TInt64StringPair.Create(1316, 'one thousand three hundred sixteen'));
  FMatches.Add(TInt64StringPair.Create(1000000, 'one million'));
  FMatches.Add(TInt64StringPair.Create(2000000, 'two millions'));
  FMatches.Add(TInt64StringPair.Create(3000200, 'three millions two hundred'));
  FMatches.Add(TInt64StringPair.Create(700000, 'seven hundred thousand'));
  FMatches.Add(TInt64StringPair.Create(9000000, 'nine millions'));
  FMatches.Add(TInt64StringPair.Create(9001000, 'nine millions one thousand'));
  FMatches.Add(TInt64StringPair.Create(123456789, 'one hundred twenty three millions four hundred fifty six thousand seven hundred eighty nine'));
  FMatches.Add(TInt64StringPair.Create(2147483647, 'two billions one hundred forty seven millions four hundred eighty three thousand six hundred forty seven'));
  FMatches.Add(TInt64StringPair.Create(3000000010, 'three billions ten'));
end;

procedure TestTEnglishNumber2DecimalString.TearDown;
begin
  FMatches.Free;
  FMatches := nil;
  inherited TearDown();
end;

procedure TestTEnglishNumber2DecimalString.TestNumber2String;
var
  Match: TInt64StringPair;
  Result: string;
  Key: Int64;
  Value: string;
begin
  CheckTrue(FMatches.Count > 0, 'Matches.Count must be larger than zero');
  for Match in FMatches do
  begin
    Key := Match.Key;
    Result := Number2String.ToString(Key);
    Value := Match.Value;
    if Result <> Value then // retry for debugging
      Result := Number2String.ToString(Key);
    Self.CheckEquals(Value, Result, Format('Key=%d', [Key]));
  end;
end;

procedure TestTDutchNumber2DecimalString.AddMatches;
begin
  FMatches.Add(TInt64StringPair.Create(TAbstractNumber2DecimalString.Zero, 'nul'));
  FMatches.Add(TInt64StringPair.Create(1000, 'duizend'));

  FMatches.Add(TInt64StringPair.Create(20000000000, 'twintig miljard')); // (2 * 10^11)
  // list adapted from Roman.
  // spelling for some numbers: http://nl.wikipedia.org/wiki/Lijst_van_natuurlijke_getallen
  // http://nl.wikipedia.org/wiki/Hoofdtelwoord#Schrijfwijze
  // http://www.onzetaal.nl/advies/getallen.php (leading for 'en')
  // leading: http://taaladvies.net/taal/advies/vraag/1302, http://taaladvies.net/taal/advies/tekst/44, http://woordenlijst.org/leidraad/6/9/, http://taaladvies.net/taal/advies/vraag/1292
  FMatches.Add(TInt64StringPair.Create(0, 'nul'));
  FMatches.Add(TInt64StringPair.Create(1, 'een'));
  FMatches.Add(TInt64StringPair.Create(2, 'twee'));
  FMatches.Add(TInt64StringPair.Create(3, 'drie'));
  FMatches.Add(TInt64StringPair.Create(4, 'vier'));
  FMatches.Add(TInt64StringPair.Create(5, 'vijf'));
  FMatches.Add(TInt64StringPair.Create(6, 'zes'));
  FMatches.Add(TInt64StringPair.Create(7, 'zeven'));
  FMatches.Add(TInt64StringPair.Create(8, 'acht'));
  FMatches.Add(TInt64StringPair.Create(9, 'negen'));
  FMatches.Add(TInt64StringPair.Create(10, 'tien'));
  FMatches.Add(TInt64StringPair.Create(11, 'elf'));
  FMatches.Add(TInt64StringPair.Create(12, 'twaalf'));
  FMatches.Add(TInt64StringPair.Create(13, 'dertien'));
  FMatches.Add(TInt64StringPair.Create(14, 'veertien'));
  FMatches.Add(TInt64StringPair.Create(15, 'vijftien'));
  FMatches.Add(TInt64StringPair.Create(16, 'zestien'));
  FMatches.Add(TInt64StringPair.Create(17, 'zeventien'));
  FMatches.Add(TInt64StringPair.Create(18, 'achttien'));
  FMatches.Add(TInt64StringPair.Create(19, 'negentien'));
  FMatches.Add(TInt64StringPair.Create(20, 'twintig'));
  FMatches.Add(TInt64StringPair.Create(21, 'eenentwintig'));
  FMatches.Add(TInt64StringPair.Create(25, 'vijfentwintig'));
  FMatches.Add(TInt64StringPair.Create(30, 'dertig'));
  FMatches.Add(TInt64StringPair.Create(35, 'vijfendertig'));
  FMatches.Add(TInt64StringPair.Create(40, 'veertig'));
  FMatches.Add(TInt64StringPair.Create(45, 'vijfenveertig'));
  FMatches.Add(TInt64StringPair.Create(49, 'negenenveertig'));
  FMatches.Add(TInt64StringPair.Create(50, 'vijftig'));
  FMatches.Add(TInt64StringPair.Create(60, 'zestig'));
  FMatches.Add(TInt64StringPair.Create(69, 'negenenzestig'));
  FMatches.Add(TInt64StringPair.Create(70, 'zeventig'));
  FMatches.Add(TInt64StringPair.Create(76, 'zesenzeventig'));
  FMatches.Add(TInt64StringPair.Create(80, 'tachtig'));
  FMatches.Add(TInt64StringPair.Create(90, 'negentig'));
  FMatches.Add(TInt64StringPair.Create(99, 'negenennegentig'));
  FMatches.Add(TInt64StringPair.Create(100, 'honderd'));
  FMatches.Add(TInt64StringPair.Create(110, 'honderdtien'));
  FMatches.Add(TInt64StringPair.Create(150, 'honderdvijftig'));
  FMatches.Add(TInt64StringPair.Create(200, 'tweehonderd'));
  FMatches.Add(TInt64StringPair.Create(300, 'driehonderd'));
  FMatches.Add(TInt64StringPair.Create(400, 'vierhonderd'));
  FMatches.Add(TInt64StringPair.Create(499, 'vierhonderdnegenennegentig'));
  FMatches.Add(TInt64StringPair.Create(500, 'vijfhonderd'));
  FMatches.Add(TInt64StringPair.Create(600, 'zeshonderd'));
  FMatches.Add(TInt64StringPair.Create(666, 'zeshonderdzesenzestig'));
  FMatches.Add(TInt64StringPair.Create(700, 'zevenhonderd'));
  FMatches.Add(TInt64StringPair.Create(800, 'achthonderd'));
  FMatches.Add(TInt64StringPair.Create(900, 'negenhonderd'));
  FMatches.Add(TInt64StringPair.Create(999, 'negenhonderdnegenennegentig'));
  FMatches.Add(TInt64StringPair.Create(1000, 'duizend'));
  FMatches.Add(TInt64StringPair.Create(1444, 'duizend vierhonderdvierenveertig')); //'veertienhonderdvierenveertig'
  FMatches.Add(TInt64StringPair.Create(1666, 'duizend zeshonderdzesenzestig'));
  FMatches.Add(TInt64StringPair.Create(1990, 'duizend negenhonderdnegentig'));
  FMatches.Add(TInt64StringPair.Create(1999, 'duizend negenhonderdnegenennegentig'));
  FMatches.Add(TInt64StringPair.Create(2000, 'tweeduizend'));
  FMatches.Add(TInt64StringPair.Create(2001, 'tweeduizend een'));
  FMatches.Add(TInt64StringPair.Create(2010, 'tweeduizend tien'));
  FMatches.Add(TInt64StringPair.Create(2012, 'tweeduizend twaalf'));
  FMatches.Add(TInt64StringPair.Create(2500, 'tweeduizend vijfhonderd'));
  FMatches.Add(TInt64StringPair.Create(3000, 'drieduizend'));
  FMatches.Add(TInt64StringPair.Create(3888, 'drieduizend achthonderdachtentachtig'));
  FMatches.Add(TInt64StringPair.Create(3999, 'drieduizend negenhonderdnegenennegentig'));
  FMatches.Add(TInt64StringPair.Create(4000, 'vierduizend'));
  FMatches.Add(TInt64StringPair.Create(5000, 'vijfduizend'));
  FMatches.Add(TInt64StringPair.Create(6666, 'zesduizend zeshonderdzesenzestig'));
  FMatches.Add(TInt64StringPair.Create(10000, 'tienduizend'));
  FMatches.Add(TInt64StringPair.Create(50000, 'vijftigduizend'));
  FMatches.Add(TInt64StringPair.Create(100000, 'honderdduizend'));
  FMatches.Add(TInt64StringPair.Create(500000, 'vijfhonderdduizend'));
  FMatches.Add(TInt64StringPair.Create(1000000, 'een miljoen'));
  FMatches.Add(TInt64StringPair.Create(1444000, 'een miljoen vierhonderdvierenveertigduizend'));
  FMatches.Add(TInt64StringPair.Create(1666000, 'een miljoen zeshonderdzesenzestigduizend'));
  FMatches.Add(TInt64StringPair.Create(2000000, 'twee miljoen'));
  FMatches.Add(TInt64StringPair.Create(3888000, 'drie miljoen achthonderdachtentachtigduizend'));
  FMatches.Add(TInt64StringPair.Create(-3888000, 'min drie miljoen achthonderdachtentachtigduizend'));
  // http://www.rgagnon.com/javadetails/java-0426.html
  FMatches.Add(TInt64StringPair.Create(0, 'nul'));
  FMatches.Add(TInt64StringPair.Create(1, 'een'));
  FMatches.Add(TInt64StringPair.Create(16, 'zestien'));
  FMatches.Add(TInt64StringPair.Create(100, 'honderd'));
  FMatches.Add(TInt64StringPair.Create(118, 'honderdachttien'));
  FMatches.Add(TInt64StringPair.Create(200, 'tweehonderd'));
  FMatches.Add(TInt64StringPair.Create(219, 'tweehonderdnegentien'));
  FMatches.Add(TInt64StringPair.Create(800, 'achthonderd'));
  FMatches.Add(TInt64StringPair.Create(801, 'achthonderdeen'));
  FMatches.Add(TInt64StringPair.Create(1316, 'duizend driehonderdzestien'));
  FMatches.Add(TInt64StringPair.Create(1000000, 'een miljoen'));
  FMatches.Add(TInt64StringPair.Create(2000000, 'twee miljoen'));
  FMatches.Add(TInt64StringPair.Create(3000200, 'drie miljoen tweehonderd'));
  FMatches.Add(TInt64StringPair.Create(700000, 'zevenhonderdduizend'));
  FMatches.Add(TInt64StringPair.Create(9000000, 'negen miljoen'));
  FMatches.Add(TInt64StringPair.Create(9001000, 'negen miljoen duizend'));
  FMatches.Add(TInt64StringPair.Create(123456789, 'honderddrieentwintig miljoen vierhonderdzesenvijftigduizend zevenhonderdnegenentachtig'));
  FMatches.Add(TInt64StringPair.Create(2147483647, 'twee miljard honderdzevenenveertig miljoen vierhonderddrieentachtigduizend zeshonderdzevenenveertig'));
  FMatches.Add(TInt64StringPair.Create(3000000010, 'drie miljard tien'));
end;

function TestTDutchNumber2DecimalString.CreateNumber2String: INumber2String;
begin
  Result := TDutchNumber2DecimalString.Create;
end;

procedure TestTDutchNumber2DecimalString.SetUp;
begin
  inherited;
  FNumber2String := CreateNumber2String(); // TNumber2String.Create;
  FMatches := TInt64StringPairList.Create();
  AddMatches();
end;

procedure TestTDutchNumber2DecimalString.TearDown;
begin
  FMatches.Free;
  FMatches := nil;
  inherited TearDown();
end;

procedure TestTDutchNumber2DecimalString.TestNumber2String;
var
  Match: TInt64StringPair;
  Result: string;
  Key: Int64;
  Value: string;
begin
  CheckTrue(FMatches.Count > 0, 'Matches.Count must be larger than zero');
  for Match in FMatches do
  begin
    Key := Match.Key;
    Result := Number2String.ToString(Key);
    Value := Match.Value;
    if Result <> Value then // retry for debugging
      Result := Number2String.ToString(Key);
    Self.CheckEquals(Value, Result, Format('Key=%d', [Key]));
  end;
end;

procedure TestTGermanNumber2DecimalString.AddMatches;
begin
  FMatches.Add(TInt64StringPair.Create(TAbstractNumber2DecimalString.Zero, 'null'));
  FMatches.Add(TInt64StringPair.Create(1000, 'tausend'));

//  FMatches.Add(TInt64StringPair.Create(20000000000, 'twintig miljard'); // (2 * 10^11)

  FMatches.Add(TInt64StringPair.Create(0, 'null'));
  FMatches.Add(TInt64StringPair.Create(1, 'eins'));
  FMatches.Add(TInt64StringPair.Create(2, 'zwei'));
  FMatches.Add(TInt64StringPair.Create(3, 'drei'));

  FMatches.Add(TInt64StringPair.Create(4, 'vier'));
  FMatches.Add(TInt64StringPair.Create(5, 'fünf'));
  FMatches.Add(TInt64StringPair.Create(6, 'sechs'));
  FMatches.Add(TInt64StringPair.Create(7, 'sieben'));

  FMatches.Add(TInt64StringPair.Create(8, 'acht'));
  FMatches.Add(TInt64StringPair.Create(9, 'neun'));
  FMatches.Add(TInt64StringPair.Create(10, 'zehn'));
  FMatches.Add(TInt64StringPair.Create(11, 'elf'));

  FMatches.Add(TInt64StringPair.Create(12, 'zwölf'));
  FMatches.Add(TInt64StringPair.Create(13, 'dreizehn'));
  FMatches.Add(TInt64StringPair.Create(14, 'vierzehn'));

  FMatches.Add(TInt64StringPair.Create(15, 'fünfzehn'));
  FMatches.Add(TInt64StringPair.Create(16, 'sechszehn'));
  FMatches.Add(TInt64StringPair.Create(17, 'siebzehn'));

  FMatches.Add(TInt64StringPair.Create(18, 'achtzehn'));
  FMatches.Add(TInt64StringPair.Create(19, 'neunzehn'));
  FMatches.Add(TInt64StringPair.Create(20, 'zwanzig'));

  FMatches.Add(TInt64StringPair.Create(21, 'einundzwanzig'));
  FMatches.Add(TInt64StringPair.Create(25, 'fünfundzwanzig'));
  FMatches.Add(TInt64StringPair.Create(30, 'dreißig'));

  FMatches.Add(TInt64StringPair.Create(35, 'fünfunddreißig'));
  FMatches.Add(TInt64StringPair.Create(40, 'vierzig'));
  FMatches.Add(TInt64StringPair.Create(45, 'fünfundvierzig'));

  FMatches.Add(TInt64StringPair.Create(49, 'neunundvierzig'));
  FMatches.Add(TInt64StringPair.Create(50, 'fünfzig'));
  FMatches.Add(TInt64StringPair.Create(60, 'sechzig'));

  FMatches.Add(TInt64StringPair.Create(69, 'neunundsechzig'));
  FMatches.Add(TInt64StringPair.Create(70, 'siebzig'));
  FMatches.Add(TInt64StringPair.Create(76, 'sechsundsiebzig'));

  FMatches.Add(TInt64StringPair.Create(80, 'achtzig'));
  FMatches.Add(TInt64StringPair.Create(90, 'neunzig'));
  FMatches.Add(TInt64StringPair.Create(99, 'neunundneunzig'));

  FMatches.Add(TInt64StringPair.Create(100, 'hundert'));
  FMatches.Add(TInt64StringPair.Create(110, 'hundertzehn'));
  FMatches.Add(TInt64StringPair.Create(150, 'hundertfünfzig'));

  FMatches.Add(TInt64StringPair.Create(200, 'zweihundert'));
  FMatches.Add(TInt64StringPair.Create(300, 'dreihundert'));
  FMatches.Add(TInt64StringPair.Create(400, 'vierhundert'));

  FMatches.Add(TInt64StringPair.Create(499, 'vierhundertneunundneunzig'));
  FMatches.Add(TInt64StringPair.Create(500, 'fünfhundert'));

  FMatches.Add(TInt64StringPair.Create(600, 'sechshundert'));
  FMatches.Add(TInt64StringPair.Create(666, 'sechshundertsechsundsechzig'));

  FMatches.Add(TInt64StringPair.Create(700, 'siebenhundert'));
  FMatches.Add(TInt64StringPair.Create(800, 'achthundert'));

  FMatches.Add(TInt64StringPair.Create(900, 'neunhundert'));
  FMatches.Add(TInt64StringPair.Create(999, 'neunhundertneunundneunzig'));

  FMatches.Add(TInt64StringPair.Create(1000, 'tausend'));
  FMatches.Add(TInt64StringPair.Create(1444, 'eintausendvierhundertvierundvierzig')); //'veertienhonderdvierenveertig'
  FMatches.Add(TInt64StringPair.Create(1666, 'eintausendsechshundertsechsundsechzig'));

  FMatches.Add(TInt64StringPair.Create(1990, 'eintausendneunhundertneunzig'));

  FMatches.Add(TInt64StringPair.Create(1999, 'eintausendneunhundertneunundneunzig'));
  FMatches.Add(TInt64StringPair.Create(2000, 'zweitausend'));

  FMatches.Add(TInt64StringPair.Create(2001, 'zweitausendeins'));
  FMatches.Add(TInt64StringPair.Create(2010, 'zweitausendzehn'));

  FMatches.Add(TInt64StringPair.Create(2012, 'zweitausendzwölf'));
  FMatches.Add(TInt64StringPair.Create(2500, 'zweitausendfünfhundert'));

  FMatches.Add(TInt64StringPair.Create(3000, 'dreitausend'));
  FMatches.Add(TInt64StringPair.Create(3888, 'dreitausendachthundertachtundachtzig'));

  FMatches.Add(TInt64StringPair.Create(3999, 'dreitausendneunhundertneunundneunzig'));
  FMatches.Add(TInt64StringPair.Create(4000, 'viertausend'));

  FMatches.Add(TInt64StringPair.Create(5000, 'fünftausend'));
  FMatches.Add(TInt64StringPair.Create(6666, 'sechstausendsechshundertsechsundsechzig'));

  FMatches.Add(TInt64StringPair.Create(10000, 'zehntausend'));
  FMatches.Add(TInt64StringPair.Create(50000, 'fünfzigtausend'));

  FMatches.Add(TInt64StringPair.Create(100000, 'einhunderttausend'));
  FMatches.Add(TInt64StringPair.Create(500000, 'fünfhunderttausend'));

  FMatches.Add(TInt64StringPair.Create(1000000, 'einemillion'));
  FMatches.Add(TInt64StringPair.Create(1444000, 'einemillionvierhundertvierzigtausend'));

  FMatches.Add(TInt64StringPair.Create(1666000, 'einemillionsechshundertsechzigtausend'));
  FMatches.Add(TInt64StringPair.Create(2000000, 'zweimillionen'));
  FMatches.Add(TInt64StringPair.Create(3888000, 'dreimillionenachthundertachtundachtzigtausend'));
  FMatches.Add(TInt64StringPair.Create(-3888000, 'minus dreimillionenachthundertachtundachtzigtausend '));

// http://www.rgagnon.com/javadetails/java-0426.html

  FMatches.Add(TInt64StringPair.Create(0, 'null'));
  FMatches.Add(TInt64StringPair.Create(1, 'eins'));
  FMatches.Add(TInt64StringPair.Create(16, 'sechszehn'));

  FMatches.Add(TInt64StringPair.Create(100, 'hundert'));
  FMatches.Add(TInt64StringPair.Create(118, 'hundertachtzehn'));
  FMatches.Add(TInt64StringPair.Create(200, 'zweihundert'));

  FMatches.Add(TInt64StringPair.Create(219, 'zweihundertneunzehn'));
  FMatches.Add(TInt64StringPair.Create(800, 'achthundert'));

  FMatches.Add(TInt64StringPair.Create(801, 'achthunderteins'));
  FMatches.Add(TInt64StringPair.Create(1316, 'eintausenddreihundertsechszehn'));

  FMatches.Add(TInt64StringPair.Create(1000000, 'einemillion'));
  FMatches.Add(TInt64StringPair.Create(2000000, 'zweimillionen'));

  FMatches.Add(TInt64StringPair.Create(3000200, 'dreimillionenzweihundert'));
  FMatches.Add(TInt64StringPair.Create(700000, 'siebenhunderttausend'));

  FMatches.Add(TInt64StringPair.Create(9000000, 'neunmillionen'));
  FMatches.Add(TInt64StringPair.Create(9001000, 'neunmillioneneintausend'));


  // list adapted from Roman.
  // spelling for some numbers: http://nl.wikipedia.org/wiki/Lijst_van_natuurlijke_getallen
  // http://nl.wikipedia.org/wiki/Hoofdtelwoord#Schrijfwijze
  // http://www.onzetaal.nl/advies/getallen.php (leading for 'en')
  // leading: http://taaladvies.net/taal/advies/vraag/1302, http://taaladvies.net/taal/advies/tekst/44, http://woordenlijst.org/leidraad/6/9/, http://taaladvies.net/taal/advies/vraag/1292
  // http://www.rgagnon.com/javadetails/java-0426.html
  FMatches.Add(TInt64StringPair.Create(123456789, 'honderddrieentwintig miljoen vierhonderdzesenvijftigduizend zevenhonderdnegenentachtig'));
  FMatches.Add(TInt64StringPair.Create(2147483647, 'twee miljard honderdzevenenveertig miljoen vierhonderddrieentachtigduizend zeshonderdzevenenveertig'));
  FMatches.Add(TInt64StringPair.Create(3000000010, 'drie miljard tien'));
end;

function TestTGermanNumber2DecimalString.CreateNumber2String: INumber2String;
begin
  Result := TGermanNumber2DecimalString.Create;
end;

procedure TestTGermanNumber2DecimalString.SetUp;
begin
  inherited;
  FNumber2String := CreateNumber2String(); // TNumber2String.Create;
  FMatches := TInt64StringPairList.Create();
  AddMatches();
end;

procedure TestTGermanNumber2DecimalString.TearDown;
begin
  FMatches.Free;
  FMatches := nil;
  inherited TearDown();
end;

procedure TestTGermanNumber2DecimalString.TestNumber2String;
var
  Match: TInt64StringPair;
  Result: string;
  Key: Int64;
  Value: string;
begin
  CheckTrue(FMatches.Count > 0, 'Matches.Count must be larger than zero');
  for Match in FMatches do
  begin
    Key := Match.Key;
    Result := Number2String.ToString(Key);
    Value := Match.Value;
    if Result <> Value then // retry for debugging
      Result := Number2String.ToString(Key);
    Self.CheckEquals(Value, Result, Format('Key=%d', [Key]));
  end;
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTGermanNumber2DecimalString.Suite);
  RegisterTest(TestTDutchNumber2DecimalString.Suite);
  RegisterTest(TestTEnglishNumber2DecimalString.Suite);

  //RegisterTest(TestTAbstractNumber2DecimalString.Suite);
end.

